nodeLinker: pnp

packageExtensions:
  gatsby-plugin-use-query-params@*:
    dependencies:
      "@emotion/react": ^11

npmRegistries:
  "https://kmong-151676761426.d.codeartifact.ap-northeast-1.amazonaws.com/npm/kmong-frontend-core/":
    npmAlwaysAuth: true
    npmAuthToken: "${CODEARTIFACT_AUTH_TOKEN:-}"

npmRegistryServer: "https://kmong-151676761426.d.codeartifact.ap-northeast-1.amazonaws.com/npm/kmong-frontend-core/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
